name: Deploy to Firebase Hosting and Functions
on:
  push:
    branches: ['main']
jobs:
  build_and_deploy:
    # if: "contains(github.event.head_commit.message, 'release-please--branches--main')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - name: download deps
        working-directory: ./functions
        run: npm ci
      - name: deploy
        run: npm i -g firebase-tools deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
