name: Deploy to Firebase Hosting
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'release-please--branches--main')"
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🫡 Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 🔨 Download dependencies and build hosting
        run: npm ci && npm run build

      - name: 🚀 Deploy to Firebase hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WALKINWALLET }}
