name: Deploy to Firebase Hosting
on:
  pull_request:
    branches: ['main']
jobs:
  deploy:
    if: "contains(github.event.head_commit.message, 'release-please--branches--main')"
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🫡 Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 🔨 Download dependencies and build hosting
        run: npm ci && npm run build

      - name: 🚀 Deploy hosting
        run: npx firebase-tools deploy --token "$FIREBASE_TOKEN" --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
